// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createBoundedAuthFetch, createBoundedAuthLock } from './authLockPolicy.mjs';

export const SUPABASE_URL = "https://rfppeuzuoxtqkpbwehbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmcHBldXp1b3h0cWtwYndlaGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTE1NTAsImV4cCI6MjA2NTU4NzU1MH0.-Km2GwsmtxHqqCLleqlf-OYgYo2U9DYG492bcRkj2W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    // Only Auth endpoints receive a network deadline. Storage uploads and
    // project data requests keep their normal long-running behavior.
    fetch: createBoundedAuthFetch(),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Supabase otherwise waits forever for the browser Auth Web Lock. A stale
    // lock in another tab must reject so the application can recover safely.
    lock: createBoundedAuthLock(),
  }
});
